### ISSUE TITLE
Configurable ways of matching

### ISSUE THREAD

**Issue by przepompownia** [phpvim/phpcd.vim#14]
Hi, 

see at the `match_subsequence` branch. You can select the old way of matching (match head), the new way (treat pattern as subsequence) and append another type of match. What do you think about merging it into master?

setMatchType() is still left as public because I tried to use it by rpcrequest(), but I have not tested it against pcntl_fork().

**Comment by lvht** [comment]
Would you like to use the YouCompleteMe plugin? With YouCompleteMe, the completion will be automatically tiggered after you enter `::`, `->`, and PHPCD will return all items. And then, YouCompleteMe will filter these items by the pattern we typed. And the matching is very smart.

**Comment by przepompownia** [comment]
I still use YCM but it is huge, depends on many other packages and require building binaries. I consider to replace it with any smaller tool. 

YCM's filter mechanism does not conflict with the proposed patch. You can still for example get full list of methods from PHPCD (after "semantic triggering" by ->) and use YCM's mechanism to filter this list without calling additional requests to completion daemon (the log file is useful to check it). But this completion does not work if I try to start completion when some part of string already exists (YCM has <C-Space> to trigger by this way).

With <C-Space> or without YCM I have only "head matching". 

Another argument: filtered list is smaller :)

**Comment by przepompownia** [comment]
Would you take a stance on merging it into master? I would not like introduce some changes without discussion.

**Comment by lvht** [comment]
i have no problem :+1:

**Comment by przepompownia** [comment]
Merged :)
