### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by wysiecki** [phpvim/phpcd.vim#29]
Hi, maybe silly, but i can't get the plugin running.

requirements are set

ran composer update (in my project, however do not understand what should happen here, nothing's changed in my composer.json)

getting in nvim E117: Unknown function: phpcd

Want to try this out badly, as of lacking in any "real" php autocomplete

I'm on OSX El Capitan

THX
Martin

**Comment by lvht** [comment]
@wysiecki Please offer you init.vim and the full error message. Thanks.

**Comment by lvht** [comment]
Hello @wysiecki ?
