### ISSUE TITLE
Invalid channel "4"

### ISSUE THREAD

**Issue by davidosomething** [phpvim/phpcd.vim#30]
Pretty sure I have this installed correctly

Using vim-plug and did composer update from within the `phpcd.vim/` directory where its `composer.json` is.

When typing to complete something, I get this message:

```
Error detected while processing function phpcd#CompletePHP..phpcd#GetCurrentNameSpace:                                                           
line    1:                                                                                                                                       
Invalid channel "4"     
```

**Comment by lvht** [comment]
Please offer more information. I cannot reoccur your problem.

**Comment by davidosomething** [comment]
- Arch linux
- python3:
    - msgpack-python (0.4.7)
    - neovim (0.1.3)
- NeoVIM 0.1.2
    - phpcd.vim installed via vim-plug
    - cd'd into phpcd.vim plugin dir and ran `composer update`
    - vim-scripts/progressbar-widget installed via vim-plug
    - verified that `omnifunc=phpcd#CompletePHP`
- Composer version 1.0-dev (3cea62b6ed8220cca53721a3210fbf64a08170dc) 2016-03-04 15:39:36


Composer project is brand new project -- empty

## composer.json:

```
{
    "name": "davidosomething/test-composer-project",
    "require": {
        "monolog/monolog": "^1.18"
    },
    "authors": [
        {
            "name": "David O'Trakoun",
            "email": "me@davidosomething.com"
        }
    ]
}
```

## index.php

```
<?php
```


If I start typing `use Monolog\` and then `<C-x><C-o>` to trigger completion i get the invalid channel "4" error.

**Comment by lvht** [comment]
Thanks for your patience. But phpcd can not complete namespace and classname, none of which could be feched by the Reflection. Only global function and class member completion is supported until now.
