### ISSUE TITLE
Error E730 using List as a String

### ISSUE THREAD

**Issue by Xerkus** [phpvim/phpcd.vim#41]
Getting error for code like this:

```php
$entity = $this->someRepo->find();
$entity->g<autocompletion here triggers error>
```

`someRepo` property is annotated, `find()` method is not annotated

```
Error detected while processing function phpcd#CompletePHP[61]..phpcd#GetClassName:
line  277: 
E730: using List as a String
```

call here https://github.com/phpvim/phpcd.vim/blob/443164c4df644eea9639d0a1b07f36ac343d9b7b/autoload/phpcd.vim#L843
returns `['','']` while, clearly, string is expected

**Comment by imaben** [comment]
Show your annotated

**Comment by Xerkus** [comment]
```php
namespace FooVendor\Package;

use FooVendor\Package\Model\SomeRepository;

class Bar
{
    /**
     * @var SomeRepository
     */
    protected $someRepo;

    public function __construct(SomeRepository $someRepo)
    {
        $this->someRepo = $someRepo;
    }

    public function doStuff()
    {
        $entity = $this->someRepo->find($id);
        $entity->g
    }
}
```

**Comment by lvht** [comment]
@Xerkus does the `SomeRepository->find` method has return type hinting?

**Comment by Xerkus** [comment]
no typehinting

**Comment by Xerkus** [comment]
Also, another place where list as string error appears
https://github.com/phpvim/phpcd.vim/blob/443164c4df644eea9639d0a1b07f36ac343d9b7b/autoload/phpcd.vim#L858
Besides, that part does not expect empty string and will error as well

```
$container = StaticContainerHolder::getContainer();
$container->g
```

no type hinting either

**Comment by Xerkus** [comment]
My nvim config https://github.com/Xerkus/nvim-config

**Comment by lvht** [comment]
@Xerkus you need add some `@return` comment for the `find` method

```
/**
 * @return SomeEntity|null
 */
function find()
{
}
```

**Comment by Xerkus** [comment]
to clarify: lack of autocompletion is not the problem, error is the problem here.

**Comment by lvht** [comment]
got it. Thank you @Xerkus . I'll deal with this issue tonight.

**Comment by Xerkus** [comment]
I would think this kind of error would appear in other places those functions used, under some conditions

**Comment by Xerkus** [comment]
Typo `this->g`(note missing dollar sign)  triggered error cascade
```
Error detected while processing function phpcd#CompletePHP[61]..phpcd#GetClassName[212]..phpcd#ExpandClassName:
line   11:
E684: list index out of range: 0

Error detected while processing function phpcd#CompletePHP[61]..phpcd#GetClassName[212]..phpcd#ExpandClassName: 
line   11:
E116: Invalid arguments for function has_key(a:imports, parts[0])

Error detected while processing function phpcd#CompletePHP[61]..phpcd#GetClassName[212]..phpcd#ExpandClassName:
line   11:
E15: Invalid expression: has_key(a:imports, parts[0])
```
