### ISSUE TITLE
现在是不支持vim吗？

### ISSUE THREAD

**Issue by Everything2014** [phpvim/phpcd.vim#49]
![image](https://cloud.githubusercontent.com/assets/6560524/17545495/fabae392-5f0f-11e6-9e70-e476a9ca81be.png)

我不知道是什么错误，请教下。

因为我们了文档，说目前只支持nvim，但是加了删除线。

环境都有了。composer, pcntl, json

**Comment by lvht** [comment]
支持 Vim 7.4+。Vim 从 7.4 版本引入了**Channel**和**job**特性。phpcd.vim 依赖这些特性跟后台的PHP进程通信。
