### ISSUE TITLE
`invalid channel` when `$this-><c-x><c-o>`

### ISSUE THREAD

**Issue by haoliang-gao** [phpvim/phpcd.vim#50]
![20160825_230839](https://cloud.githubusercontent.com/assets/6236829/17975380/0257b25c-6b1c-11e6-9e3d-7fc22fc6d389.jpg)

can not get any useful infomation from error, help wanted!

**Comment by haoliang-gao** [comment]
env:

* archlinux
* php 7 with pcntl extension
* nvim 0.1.5

**Comment by lvht** [comment]
Have you installed the php-msgpack extension?

**Comment by haoliang-gao** [comment]
Yeah, it works after I installed php-msgpack, thank you!

Could you add this dependency in readme ?
Or just add `"ext-msgpack": ">=2.0.1"` to composer.json ?

**Comment by lvht** [comment]
@haoliang-gao https://github.com/phpvim/phpcd.vim#环境要求

**Comment by haoliang-gao** [comment]
pu~
The 3rd text is little confuseing before I clicked in, and now I can see.
