### ISSUE TITLE
Vim hangs with 100% cpu when opening PHP file in nonexistent path 

### ISSUE THREAD

**Issue by therealgaxbo** [phpvim/phpcd.vim#51]
Attempting to open a file with a .php extension in a relative path that doesn't exist causes vim to hang with 100% cpu usage until ctrl-c is pressed.  E.g.:

    vim non/existent/path.php

**Comment by lvht** [comment]
PHPCD will detect the project root directory which contains the composer.json file. If we want to edit a file under an unexist path, the root detect process failed and let cpu usage go to 100%.

It's a bug. However it is hard to fix. As PHPCD will scan the php source file to fetch some useful info. If the source path does not exist, PHPCD will not work well.

So, what we can do is to make sure that all PHP source file should be saved to the disk to let PHPCD work.

Thank you.
