### ISSUE TITLE
Omni complete "pattern not found"

### ISSUE THREAD

**Issue by shadowhand** [phpvim/phpcd.vim#52]
If anyone is getting the a "pattern not found" error when attempting to use `CTRL X CTRL O`, and you are using Pathogen, the problem is Pathogen itself. **PHPCD does not work with Pathogen!**

Replacing Pathogen with [vim-plug](https://github.com/junegunn/vim-plug), as per the README, allows PHPCD to work properly.

I am submitting this issue for anyone else that might run into this problem.

**Comment by przepompownia** [comment]
Hi, I had not use phpcd without Pathogen (unless for rare debug purposes). Probably the error lies somewhere else.

**Comment by lvht** [comment]
Have you  added the `autocmd FileType php setlocal omnifunc=phpcd#CompletePHP` to your vimrc?

It works well for me under Vim 8.0.19 with Pathogen.
