### ISSUE TITLE
Jumping back from definition

### ISSUE THREAD

**Issue by shadowhand** [phpvim/phpcd.vim#58]
Using tags, when we use `C + ]` to jump to a definition, we can jump back to where we were using `C + t`. With PHPCD, this command results in an error:

```
E73: Tag stack empty
```

**Comment by lvht** [comment]
I use `C + o`.

**Comment by lvht** [comment]
phpcd.vim has remapped the `C + ]` and never maintain the tag stack. This is why the `C + t` do not work. Just use `C + o`.

**Comment by lvht** [comment]
It seems to be a problem. Sorry.

**Comment by lvht** [comment]
Fixed at a95229c83c244e4d717966b04d44a0b477a40f70

**Comment by shadowhand** [comment]
Thank you!
