### ISSUE TITLE
Jumping to definition of class fails without namespace

### ISSUE THREAD

**Issue by shadowhand** [phpvim/phpcd.vim#59]
I have a class that is defined something like:

```php
<?php
class Controller_Foo extends Controller { ... }
```

When I try to use `C + ]` to jump to the source of `Controller`, the following error trace appears:

```
Error detected while processing function phpcd#JumpToDefinition[5]..phpcd#GetCurrentSymbolWithContext[41]..phpcd#GetCurrentNameSpace[1]..rpc#request:
line    6:
E714: List required
line    7:
E121: Undefined variable: error
E15: Invalid expression: error
line   10:
E121: Undefined variable: response
E15: Invalid expression: response
Error detected while processing function phpcd#JumpToDefinition[5]..phpcd#GetCurrentSymbolWithContext[41]..phpcd#GetCurrentNameSpace:
line    3:
E121: Undefined variable: namespace
E15: Invalid expression: [nsuse.namespace, nsuse.imports]
Error detected while processing function phpcd#JumpToDefinition[5]..phpcd#GetCurrentSymbolWithContext:
line   41:
E714: List required
line   43:
E121: Undefined variable: current_namespace
E116: Invalid arguments for function phpcd#ExpandClassName(word, current_namespace, current_imports)
E15: Invalid expression: phpcd#ExpandClassName(word, current_namespace, current_imports)
line   48:
E121: Undefined variable: symbol
E15: Invalid expression: [symbol, context, symbol_namespace, current_imports]
Error detected while processing function phpcd#JumpToDefinition:
line    5:
E714: List required
line    6:
E121: Undefined variable: symbol
E15: Invalid expression: symbol == ''
line   10:
E121: Undefined variable: symbol
E116: Invalid arguments for function phpcd#LocateSymbol(symbol, symbol_context, symbol_namespace, current_imports)
E15: Invalid expression: phpcd#LocateSymbol(symbol, symbol_context, symbol_namespace, current_imports)
line   11:
E121: Undefined variable: symbol_file
E15: Invalid expression: symbol_file == ''
line   21:
E121: Undefined variable: symbol_line
E116: Invalid arguments for function str2nr(symbol_line) > 0
E15: Invalid expression: str2nr(symbol_line) > 0
```

It looks like the root cause of the error is that neither class is defined in a namespace.

**Comment by lvht** [comment]
Can the `Controller` class be autoloaded by php?

**Comment by shadowhand** [comment]
Yes, PHP handles autoloading but not using Composer.

**Comment by lvht** [comment]
PHPCD use composer's autoload to load class and fetch meta info, which is configured at https://github.com/phpvim/phpcd.vim/blob/master/php/main.php#L32 .

If you just want to let phpcd work, just make a `vendor/autoload.php` and register your own autoload function there.

Maybe phpcd need to support some config to change the autoload file, instead of hard code the `vendor/autoload.php`.

**Comment by shadowhand** [comment]
This project uses both `vendor/autoload.php` and a custom autoloader. 😨 Having some way to attach multiple autoloaders on a per-project basis would be hugely beneficial.

Is there any way to prevent PHPCD from taking over `C + ]` functionality so that I can rely on tags instead?

**Comment by lvht** [comment]
Fixed it at https://github.com/phpvim/phpcd.vim/blob/master/plugin/phpcd.vim#L7

You could set your own autoload file path in your vimrc

```
let g:phpcd_autoload_path="foo/bar/autoload.php"
```

The path is **relative** to you project's root path.
