### ISSUE TITLE
Both servers exit short time after starting 

### ISSUE THREAD

**Issue by paprykarz** [phpvim/phpcd.vim#9]
Hi,

I could not find, why main (freshly moved to RPCServer) loop exits about after one minute from start.

`Error detected while processing function   phpcd#CompletePHP..phpcd#GetCurrentNameSpace:                                                                             line    1:                                                                                                                                                    
Invalid channel "1"  `

Regards

**Comment by lvht** [comment]
I encountered this problem, too. Weird!

**Comment by lvht** [comment]
Maybe the reason has been found at 75751c4dc542a2f43003818b6154021f4c7a40b1

**Comment by paprykarz** [comment]
It works. Thanks!
